FROM node:22-slim

WORKDIR /app
ENV NODE_ENV=production
ENV NODE_OPTIONS="--dns-result-order=ipv4first"
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
RUN npm install -g pnpm@11.13.1

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm --filter web build

EXPOSE 3000
CMD ["pnpm", "--filter", "web", "start"]
