packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '0': '@prisma/engines'
  '1': prisma
  '2': unrs-resolver
  '@prisma/engines': set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
